name: Update Data

on:
  push:
    branches:
      - main
    paths:
      - 'data/recipes.json'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate graph data
        run: node lib/graph-generator.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/graph-data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update graph data" && git push)